### ISSUE TITLE
translate spike

### ISSUE THREAD

**Issue by MSakamaki** [MSakamaki/angular-checklist#1]
https://github.com/angular-checklist/angular-checklist/issues/45

## TASKS (feature)

 + [x] translation feature by i18n
 + [x] markdown translation feature
 + [x] firebase redirect settings
 + [x] change the directory structure of content
 + meta data
    + [ ] lang attribute
    + [ ] meta name="description" 

## translation

 + [x] application
 + [content
    + [x] architecture
    + [x] components
    + [x] general
    + [x] http
    + [x] ngrx
    + [x] performancerouter
    + [x] router
    + [x] rxjs
    + [x] tooling
    + [ ] typescript

## NOTE

We are currently working on a sample that works with /en/ and /ja/ paths on forked branches.
(It is easy to translate using `ngx-translate` instead of angular i18n, but Universal seems to have problems.)

We are currently examining the content translation process generated from markdown.

I found that I could solve the firebase redirect configuration as follows.
https://firebase.google.com/docs/hosting/full-config

**Comment by MSakamaki** [comment]
angular i18n Locale
https://angular.io/guide/i18n#setting-up-the-locale-of-your-app

**Comment by MSakamaki** [comment]
# MEMO

I translated the architecture but I can notice the problem.
If translate multiple languages as it is, maintainability will be lost.

before
```
content/architecture/
├── never-mutate-objects.md
├── provide-shared-services-on-root-level.md
├── put-business-logic-into-services.md
├── use-descriptive-file-names.md
└── use-smart-and-dumb-components.md
```
after
```
content/architecture/
├── never-mutate-objects.ja.md
├── never-mutate-objects.md
├── provide-shared-services-on-root-level.ja.md
├── provide-shared-services-on-root-level.md
├── put-business-logic-into-services.ja.md
├── put-business-logic-into-services.md
├── use-descriptive-file-names.ja.md
├── use-descriptive-file-names.md
├── use-smart-and-dumb-components.ja.md
└── use-smart-and-dumb-components.md
```

I should stop extension based copying and switch to the top path.

```
content/
├── en-US/architecture
│   ├── never-mutate-objects.md
│   ├── provide-shared-services-on-root-level.md
│   ├── put-business-logic-into-services.md
│   ├── use-descriptive-file-names.md
│   └── use-smart-and-dumb-components.md
└── ja/architecture
    ├── never-mutate-objects.md
    ├── provide-shared-services-on-root-level.md
    ├── put-business-logic-into-services.md
    ├── use-descriptive-file-names.md
    └── use-smart-and-dumb-components.md
```

**Comment by MSakamaki** [comment]
The language selector needed accessibility.
Add it

## Resources

https://terrillthompson.com/759

**Comment by MSakamaki** [comment]
problem.
Incomplete lang attributes and metadata
It is necessary to consider how to handle this.


```
<html lang="en">
  <head></head>
  <meta name="description" content="Angular Checklist is a curated list of best practices for Angular apps. It’s a todo application where each item represents one best practice. You can use it for code reviews or as a style guide for your applications.">
```
